### ISSUE TITLE
Cannot reproduce the result, actually a really bad one if training from scratch

### ISSUE THREAD

**Issue by arxrean** [Fengdalu/LipNet-PyTorch#12]
Hi Fengdalu,
Thanks for sharing the code. However, if I train the model from scratch without pretrained weights and keep the options same, the result is very bad (like 0.8 WER for test?). Is there any preprocess if I want to train from zero? Thank you!

**Comment by Fengdalu** [comment]
When start from scratch,the base_lr should be 1e-4 instead of 1e-5.
