### ISSUE TITLE
About extract_lip.py and face_det_sfd.py 

### ISSUE THREAD

**Issue by FariaKP** [Fengdalu/LipNet-PyTorch#13]
There is no such a file like "grid.txt" and "imgs.txt" which you have mentioned in extract_lip.py and face_det_sfd.py respectively. What is the purpose of these two files?  Can you kindly clarify?
Thank you.

**Comment by Fengdalu** [comment]
The "grid.txt" and "imgs.txt"  contain the raw data, one path per line. The `face_det_sfd.py` is used to detect face from the raw scene, especially the bounding box and the landmark. The `extract_lip.py` read the landmark and extracts lip from the original scene.

**Comment by FariaKP** [comment]
@Fengdalu Thank you very much for your reply.

1. can you kindly tell me for "demo.py", which should the directory for video dataset and which should be the directory for extracted image dataset?

2. after successful compilation of "demo.py" what will be tha output of this file. I mean how will the output of demo.py look like. Will it be similar to demo.gif? 
Thank you.

**Comment by Fengdalu** [comment]
> @Fengdalu Thank you very much for your reply.
> 
> 1. can you kindly tell me for "demo.py", which should be the directory for video dataset and which should be the directory for extracted image dataset?
> 2. after successful compilation of "demo.py" what will be tha output of this file. I mean how will the output of demo.py look like. Will it be similar to demo.gif?
>    Thank you.

1. `demo.py` take a single video file as input such as .mp4, .avi. The dictionary is not fixed, which can be passed by the first parameter in commond line and the output file is the second parameter.  such as `python demo.py 123.mp4 demo.gif`
 2. Yes
