### ISSUE TITLE
The question about parameters initialization.

### ISSUE THREAD

**Issue by lzkzls** [Fengdalu/LipNet-PyTorch#15]
Thanks for sharing! After reading your code, I want to ask you a question. In the GRU initializing, you use this formula "stdv = math.sqrt(2 / (96 * 3 * 6 + 256))" to compute stdv. Could you tell me what 96 3  256 mean?  And why you use "math.sqrt(3) * stdv" in the "init.uniform_"?

**Comment by Fengdalu** [comment]
I use orthogonal initialization for grus in this project. In fact, it won't affect the final performance a lot.
