### ISSUE TITLE
Affine transformation

### ISSUE THREAD

**Issue by jxzhanggg** [Fengdalu/LipNet-PyTorch#18]
I wonder if you have any reference for computing the parameters
of affine transformation ? 
In this function, 
https://github.com/Fengdalu/LipNet-PyTorch/blob/74370eb9700b0cb1ac58842ed4d349190ca4cda1/scripts/extract_lip.py#L39-L56

**Comment by Fengdalu** [comment]
def get_position(size, padding):
 ....

**Comment by jxzhanggg** [comment]
My question is could you give any reference of how do you get this equation if possible ...
I want to read the mathematical proof of the estimation of affine transformation.
Thanks!

**Comment by Fengdalu** [comment]
> My question is could you give any reference of how do you get this equation if possible?
> I want to read the mathematical proof of the estimation of affine transformation.
> Thanks!

I just copy from https://github.com/davisking/dlib/blob/883101477d2485ae6e0e8499ec0eefb8382fcb5a/dlib/image_transforms/interpolation.h

**Comment by jxzhanggg** [comment]
That's very helpful, thank u!

**Comment by LindgeW** [comment]
> > My question is could you give any reference of how do you get this equation if possible?
> > I want to read the mathematical proof of the estimation of affine transformation.
> > Thanks!
> 
> I copy standard facial points from https://github.com/davisking/dlib/blob/883101477d2485ae6e0e8499ec0eefb8382fcb5a/dlib/image_transforms/interpolation.h and apply Procrustes Analysis.

Any theoretical supports about the parameters of affine transformation ?
