### ISSUE TITLE
Where is the annotation file?

### ISSUE THREAD

**Issue by shishizhu** [Fengdalu/LipNet-PyTorch#20]
Hi, I cannot find the annotation file for this GRID dataset. And I notice that in options.py, you set the path of annotation file as:
anno_path = 'GRID_align_txt'
But where is this GRID_align_txt?

**Comment by Fengdalu** [comment]
It is the data path of the original GRID dataset. You can set it in your own setting.

**Comment by shishizhu** [comment]
> It is the data path of the original GRID dataset. You can set it in your own setting.

Thank you for your reply.
Actually, I mean I did not find those .align files. So where did you put them?

**Comment by Fengdalu** [comment]
> > It is the data path of the original GRID dataset. You can set it in your own setting.
> 
> Thank you for your reply.
> Actually, I mean I did not find those .align files. So where did you put them?

The .aligh files are the original annotation files provided by GRID, you can find it in the datasets.

**Comment by shishizhu** [comment]
> GRID

Ok, thank you very much for your time.
