### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by fawzy46** [Fengdalu/LipNet-PyTorch#22]
I get this error when I run main.py

```
self.data.append((vid, items[-4], items[-1]))

IndexError: list index out of range
```
I have only one video to test the training process can this be the issue?

**Comment by Fengdalu** [comment]
Do you use GRID corpus? The dataset.py needs to be modified by yourself when using other datasets.

**Comment by fawzy46** [comment]
yes I do but I have one video only, I have also downloaded your preprocessed data but I don't know how to use theme directly instead of videos

**Comment by Fengdalu** [comment]
Do you download the whole project, especially ``://github.com/Fengdalu/LipNet-PyTorch/tree/master/data`` folder? It contains the index files of training and testing data?
