### ISSUE TITLE
Inaccurate results.

### ISSUE THREAD

**Issue by jainnimish** [Fengdalu/LipNet-PyTorch#26]
I ran the demo.py file using a video that was saying "hello" and it predicted "BIC GREN AY J NINE LEOE". Can you please tell me why it is not correctly predicting the results. I am using the default dataset that you provided. I am running it on the GRID dataset that you gave in the repository. I did not train my own model.

Thanks.

**Comment by Fengdalu** [comment]
See issue #19. This project is trained on GRID corpus only. That means it may not fit in unseeded scenarios.
