### ISSUE TITLE
missing activation after last layer

### ISSUE THREAD

**Issue by fawzy46** [Fengdalu/LipNet-PyTorch#27]
I have noticed that there is no activation function in the forwarding after the last GRU layer, is there a specific reason for that? , as the output matrix will contain negative values which will not work with beam search as it uses the natural logarithm for scoring. 

also, are the numbers in the output matrix a probability values or just a score for every character at each time step?

thanks in advance.

**Comment by Fengdalu** [comment]
It is just a score. In training, we use `.log_softmax(-1)` to get the probability at each time step and you can follow this way in beam search.
