### ISSUE TITLE
Scripts Folder to process 

### ISSUE THREAD

**Issue by ducMNSD** [Fengdalu/LipNet-PyTorch#29]
Could you explain more clearly how to use files in scripts folder. 
In line 21, extract_frame.py : 
with open('data/GRID_files.txt', 'r') as f:
What does "GRID_files.txt" mean? 
and self.IN, self.OUT, self.wav ?
Thank you very much !!

**Comment by Fengdalu** [comment]
`GRID_files.txt` means the video list, one video per line, such as

'''
a.mp4
b.mp4
'''

**Comment by ducMNSD** [comment]
sorry but I don't understand the I/O of files in scripts folder. Could you describe the txt file paths in the 3 files in the scripts folder?
