### ISSUE TITLE
Question about align file

### ISSUE THREAD

**Issue by GKDHurryUp** [Fengdalu/LipNet-PyTorch#3]
Thank you for your sharing.I don‘t understand the meaning of .align

0 14500 sil
14500 21000 bin
21000 27750 blue
27750 33000 by
33000 40500 l
40500 50750 six
50750 60500 now
60500 74500 sil

Can you tell me what it means?

**Comment by Fengdalu** [comment]
It the origin format provided by the grid corpus.

```
start_time end_time word
```
while sil, sp mean silence times.

**Comment by GKDHurryUp** [comment]
Thanks a lot.There is another problem.I see the second line of lots of align files is "bin", is this a word or has some special meaning?

**Comment by Fengdalu** [comment]
No. Only sil and sp.
