### ISSUE TITLE
Incorrect test result for lip reading word white

### ISSUE THREAD

**Issue by Cerebex** [Fengdalu/LipNet-PyTorch#30]
Hello,

I used your pre-trained weights and foundthe predictions were great on the GRID dataset videos. On the other hand, when I say "white" over and over on video it never predicts "white" with demo.py. Do I need to edit my video other than changing it to .mp4 in any way to make this work or have you found this algorithm/pretrained weights simply do not work well when/is overtrained to GRID videos?

Regards,
Cerebex

**Comment by Fengdalu** [comment]
This project is just a reproduction of the original LipNet paper. That means it may not work well on real-world videos.

**Comment by Cerebex** [comment]
Understood. Thank you so much for your response!
