### ISSUE TITLE
why use start=1 ?

### ISSUE THREAD

**Issue by LindgeW** [Fengdalu/LipNet-PyTorch#31]
```
def txt2arr(txt, start): 
  ....

```

here why use _start_ for each char index ?

**Comment by Fengdalu** [comment]
0 is for blank in CTCLoss

**Comment by LindgeW** [comment]
Thanks for your answer! 

Another question:  
How to improve the efficiency of video processing when loading data？ It seems to be very time-consuming, and each video takes ~30 secs to load and preprocess.

**Comment by LindgeW** [comment]
Is performance gap obvious for CTC-greedy decoding and CTC-beam-search decoding?

**Comment by Fengdalu** [comment]
> Is performance gap obvious for CTC-greedy decoding and CTC-beam-search decoding?

for GRID Dataset, no obvious difference.

**Comment by LindgeW** [comment]
> > Is performance gap obvious for CTC-greedy decoding and CTC-beam-search decoding?
> 
> for GRID Dataset, no obvious difference.

how about any other datasets?
