### ISSUE TITLE
Datataset downloading from drive or dropbox

### ISSUE THREAD

**Issue by Zhaans** [Fengdalu/LipNet-PyTorch#4]
Dear Fengdalu,

Is it possible to upload the dataset to google drive or dropbox? 

Thanks a lot!

**Comment by Zhaans** [comment]
@Fengdalu sorry for bothering. Is it possible to find an alternative storage? or Baidu is the only way?
 
Thanks

**Comment by Fengdalu** [comment]
Google Drive: https://drive.google.com/drive/folders/1Wn2EJw2101nF59eNDXEto6qXqfgDDucL?usp=sharing

**Comment by Zhaans** [comment]
> Google Drive: https://drive.google.com/drive/folders/1Wn2EJw2101nF59eNDXEto6qXqfgDDucL?usp=sharing

Thanks a lot!
