### ISSUE TITLE
How to run this model on windows 10

### ISSUE THREAD

**Issue by FariaKP** [Fengdalu/LipNet-PyTorch#7]
```
cat GRID_LIP_160x80_TXT.zip.* > GRID_LIP_160x80_TXT.zip
unzip GRID_LIP_160x80_TXT.zip
rm GRID_LIP_160x80_TXT.zip
```
* As these commands are applicable for Linux, what will be the equivalent commands for windows 10.

* And can you kindly give me step by step instructions about how to run this model? I will be really grateful to you.

Thank you

**Comment by Fengdalu** [comment]
1. As these commands are applicable for Linux, what will be the equivalent commands for windows 10 ?

No.

2. And can you kindly give me step by step instructions about how to run this model? I will be really grateful to you.

I am sorry that this version only supports Linux/Unix based system.

**Comment by gilgvirts** [comment]
Maybe it should be mentioned somewhere in Readme file.

**Comment by nmstoker** [comment]
> * As these commands are applicable for Linux, what will be the equivalent commands for windows 10.

@FariaKP - I haven't tried it, but I suspect you could probably recombine and extract the files on Win10 with 7Zip, as shown here: http://mwiki.gichd.org:8090/IM/Combine_several_zip_files

Of course you may run into issues with other aspects of the repo, but maybe it gets you a little further along...
