### ISSUE TITLE
main.py is only activation script?

### ISSUE THREAD

**Issue by gilgvirts** [Fengdalu/LipNet-PyTorch#9]
Seems like main.py only runs train, since you uploaded weights already, no need for that I think. How do you run on one video selected by user? plus, can you upload a wheel file so it will be easier to install? 
thanks

**Comment by Fengdalu** [comment]
main.py includes training and testing functions, as well as the method of loading pre-trained weights. demo.py provides a simple example to run a single video.

**Comment by Unabeviable** [comment]
你好，请问你有对视频进行预处理，得到对应唇部区域的code吗？这样就不需要再次下载您提供的数据集了？谢谢！

**Comment by Fengdalu** [comment]
> 你好，请问你有对视频进行预处理，得到对应唇部区域的code吗？这样就不需要再次下载您提供的数据集了？谢谢！

在scripts文件夹中
